name: ci

on: push

jobs:
  build-static:
    name: Build static files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Build
        uses: docker://klakegg/hugo:0.81.0-busybox
        with:
          entrypoint: hugo
          args: -D --baseURL https://bogdi.xyz/
      - name: Upload static
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: public

  build-image:
    runs-on: ubuntu-latest
    needs: build-static
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: bogdi.jfrog.io
          username: ${{ secrets.JFROG_REGISTRY_USER }}
          password: ${{ secrets.JFROG_REGISTRY_PASS }}
      - name: Download static
        uses: actions/download-artifact@v2
        with:
          name: static
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            bogdi.jfrog.io/blog/bogdi:latest
            bogdi.jfrog.io/blog/bogdi:${GITHUB_SHA}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
