name: ci

on: push

jobs:
  build-static:
    name: Build static files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Run Build
        uses: docker://klakegg/hugo:0.84.4-busybox
        with:
          entrypoint: hugo
          args: -D --baseURL https://bogdi.xyz/
      - name: Upload static
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: public

  build-image:
    runs-on: ubuntu-20.04
    needs: build-static
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: bogdi.jfrog.io
          username: ${{ secrets.JFROG_REGISTRY_USER }}
          password: ${{ secrets.JFROG_REGISTRY_PASS }}
      - name: Download static
        uses: actions/download-artifact@v2
        with:
          name: static
          path: public
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            bogdi.jfrog.io/blog/bogdi:latest
            bogdi.jfrog.io/blog/bogdi:${{github.sha}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-image:
    runs-on: ubuntu-20.04
    needs: build-image
    steps:
    - name: run container using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: sudo docker rm -fv `sudo docker ps -aq` || true && sudo docker run -d --restart always -p 80:80 --pull always bogdi.jfrog.io/blog/bogdi:latest
